name: update-images

on:
  # Manual triggers
  workflow_dispatch:
  # Allows external webhook trigger
  repository_dispatch:
    types:
      - process-images

jobs:
  # Cancel any duplicate already running jobs
  pre-job:
    name: Pre-job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - name: Cancel redundant workflows
        run: echo "Cancel redundant workflows finished"
  # Update the posts list of the repo
  update:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Update post list
        run: npm run process
        env:
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
          CLOUD_API_SECRET: ${{ secrets.CLOUD_API_SECRET }}
          CDN_ROOT_URL: ${{ secrets.CDN_ROOT_URL }}
          S3_BUCKET_DIRECTORY: ${{ secrets.S3_BUCKET_DIRECTORY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_BUCKET_REGION: ${{ secrets.S3_BUCKET_REGION }}
          S3_AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
          S3_AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
      - name: Add
        run: |
          git config --global user.email "bot@vendiat.com"
          git config --global user.name "Vendia Bot"
          git status
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: update post index [skip ci]"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}