name: validate

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
    - uses: actions/checkout@v2.3.2
    - uses: bahmutov/npm-install@v1
      with:
        useLockFile: false
    - run: npm t